data_loader:
  batch_size: 4
  data_path: events/stage2/emopia_events/full_song_chord11_{}/events
  train_split: events/stage2/emopia_events/data_splits/train.pkl
  val_split: events/stage2/emopia_events/data_splits/valid.pkl
  vocab_path: events/stage2/emopia_events/full_song_chord11_{}/dictionary.pkl
model:
  d_embed: 512
  d_ff: 2048
  d_model: 512
  feature_map:
    n_dims: 128
  max_len: 3072
  n_head: 8
  n_layer: 12
  use_segemb: true
  n_segment_types: 2
training:
  gpuid: 0
  ckpt_dir: ckpt/emopia_full_song_{}
  ckpt_interval: 10
  log_interval: 50
  feat_redraw_prob: 0.05
  lr: 1.0e-05
  lr_scheduler:
    T_max: 500000
    eta_min: 1.0e-06
  num_epochs: 1000
  trained_optim: null
  trained_params: null
  inference_params: best_weight/Functional-two/emopia_acccompaniment_finetune/ep300_loss0.338_params.pt
  warmup_steps: 200